// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnZalr9fXFg_K3WiENQnOwQ93XZGPVLjE',
    appId: '1:774768252487:web:0b4e3848c4fab7872bc362',
    messagingSenderId: '774768252487',
    projectId: 'codexia--learning',
    authDomain: 'codexia--learning.firebaseapp.com',
    databaseURL: 'https://codexia--learning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codexia--learning.appspot.com',
    measurementId: 'G-343N972BLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB5fAisjBskO0sCWK2syuVMUQGva6GPFM',
    appId: '1:774768252487:android:385e5967e57e150f2bc362',
    messagingSenderId: '774768252487',
    projectId: 'codexia--learning',
    databaseURL: 'https://codexia--learning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codexia--learning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmhF-delJIcd-_OKzLKxkfLJCIlWqkUIc',
    appId: '1:774768252487:ios:b0389b28a6bc7a9e2bc362',
    messagingSenderId: '774768252487',
    projectId: 'codexia--learning',
    databaseURL: 'https://codexia--learning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codexia--learning.appspot.com',
    androidClientId: '774768252487-ovfpuuc1914p8btap66bdkgjg5fpobmg.apps.googleusercontent.com',
    iosClientId: '774768252487-15nvvs0a3h3tplndjhq6ko682s9gkppk.apps.googleusercontent.com',
    iosBundleId: 'com.codexia.codexiaLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmhF-delJIcd-_OKzLKxkfLJCIlWqkUIc',
    appId: '1:774768252487:ios:c380e063208d14ef2bc362',
    messagingSenderId: '774768252487',
    projectId: 'codexia--learning',
    databaseURL: 'https://codexia--learning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codexia--learning.appspot.com',
    androidClientId: '774768252487-ovfpuuc1914p8btap66bdkgjg5fpobmg.apps.googleusercontent.com',
    iosClientId: '774768252487-6352uchv4k4gl601f6je752i2hn9dlek.apps.googleusercontent.com',
    iosBundleId: 'com.codexia.codexiaLearning.RunnerTests',
  );
}
