// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZbWOQl4el5rw2eGSvDh-Ss7r9xGU98Go',
    appId: '1:158976799565:web:771d1ab59c0334ae6dbd04',
    messagingSenderId: '158976799565',
    projectId: 'fir-configure-8dc68',
    authDomain: 'fir-configure-8dc68.firebaseapp.com',
    databaseURL: 'https://fir-configure-8dc68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-configure-8dc68.appspot.com',
    measurementId: 'G-XVPZVSR1ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Pj-_oKfddP9yHnXQSe-O6h8MmQ5SIeU',
    appId: '1:158976799565:android:6089215483087e956dbd04',
    messagingSenderId: '158976799565',
    projectId: 'fir-configure-8dc68',
    databaseURL: 'https://fir-configure-8dc68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-configure-8dc68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbpnKU5CJ9CS7hWaEycC19O2EptavWf1w',
    appId: '1:158976799565:ios:f74ffbc3d8099b946dbd04',
    messagingSenderId: '158976799565',
    projectId: 'fir-configure-8dc68',
    databaseURL: 'https://fir-configure-8dc68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-configure-8dc68.appspot.com',
    iosBundleId: 'com.codexia.codexiaLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbpnKU5CJ9CS7hWaEycC19O2EptavWf1w',
    appId: '1:158976799565:ios:fd765c2cc4f7b3126dbd04',
    messagingSenderId: '158976799565',
    projectId: 'fir-configure-8dc68',
    databaseURL: 'https://fir-configure-8dc68-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-configure-8dc68.appspot.com',
    iosBundleId: 'com.codexia.codexiaLearning.RunnerTests',
  );
}
